In [13]:
import numpy as np
A=np.array([[1,6,3,5],[3,6,4,1],[8,4,5,6],[3,2,5,1]])
print(A)

[[1 6 3 5]
 [3 6 4 1]
 [8 4 5 6]
 [3 2 5 1]]


In [7]:
np.linalg.inv(A)

array([[-0.18243243,  0.12837838,  0.15540541, -0.14864865],
       [ 0.01689189,  0.21959459, -0.02364865, -0.16216216],
       [ 0.06756757, -0.12162162, -0.09459459,  0.35135135],
       [ 0.17567568, -0.21621622,  0.05405405,  0.01351351]])

In [8]:
np.linalg.matrix_rank(A)

4

In [9]:
np.linalg.det(A)

591.9999999999999

In [14]:
import numpy as np
B=np.array([[9,8,7,6],[3,4,6,1],[1,1,1,1],[2,3,4,5]])
print(B)

[[9 8 7 6]
 [3 4 6 1]
 [1 1 1 1]
 [2 3 4 5]]


In [15]:
print(np.array_equal(A,B))

False


In [16]:
A*B

array([[ 9, 48, 21, 30],
       [ 9, 24, 24,  1],
       [ 8,  4,  5,  6],
       [ 6,  6, 20,  5]])

In [17]:
B*5+A*3

array([[48, 58, 44, 45],
       [24, 38, 42,  8],
       [29, 17, 20, 23],
       [19, 21, 35, 28]])

In [18]:
C=np.diagflat([1,2,3,4])
print(C)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
A*C

array([[ 1,  0,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0,  4]])